name = "Hf_Timer"
version = "0.1.0"
license = "MIT"
author = "St Maxwell"
maintainer = "st_maxwell@outlook.com"
copyright = "Copyright 2021, St Maxwell"

[build]
auto-tests = true

[install]
library = true
